server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jalaxy-github/springcloud-config.git
#          uri: git@github.com:Jalaxy-github/springcloud-config.git #GitHub上面的git仓库名字
          search-paths:
            - springcloud-config
          force-pull: true
          usename: Jalaxy-github
          password: wsjxy529413
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

